sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t stephengrider/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true stephengrider/react-test npm test

after_success:
  - docker build -t moliwhale/multi-client ./client
  - docker build -t moliwhale/multi-nginx ./nginx
  - docker build -t moliwhale/multi-server ./server
  - docker build -t moliwhale/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push moliwhale/multi-client
  - docker push moliwhale/multi-nginx
  - docker push moliwhale/multi-server
  - docker push moliwhale/multi-worker
  
deploy:
  provider: elasticbeanstalk
  region: 'us-east-1'
  app: 'multi-docker'
  env: 'Multidocker-env'
  bucket_name: "elasticbeanstalk-us-east-1-578608644047"
  bucket_path: "docker-multi"
  on:
    branch: main
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
